# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'market.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\"5\n\x06Market\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\x16\n\x08MarketId\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\nMarketList\x12\x18\n\x07markets\x18\x01 \x03(\x0b\x32\x07.Market\"\x07\n\x05\x45mpty2\xbc\x01\n\rMarketService\x12#\n\x0cGetAllMarket\x12\x06.Empty\x1a\x0b.MarketList\x12 \n\x0c\x43reateMarket\x12\x07.Market\x1a\x07.Market\x12\x1f\n\tGetMarket\x12\t.MarketId\x1a\x07.Market\x12 \n\x0cUpdateMarket\x12\x07.Market\x1a\x07.Market\x12!\n\x0c\x44\x65leteMarket\x12\t.MarketId\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKET']._serialized_start=16
  _globals['_MARKET']._serialized_end=69
  _globals['_MARKETID']._serialized_start=71
  _globals['_MARKETID']._serialized_end=93
  _globals['_MARKETLIST']._serialized_start=95
  _globals['_MARKETLIST']._serialized_end=133
  _globals['_EMPTY']._serialized_start=135
  _globals['_EMPTY']._serialized_end=142
  _globals['_MARKETSERVICE']._serialized_start=145
  _globals['_MARKETSERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
