# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import market_pb2 as market__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in market_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllMarket = channel.unary_unary(
                '/MarketService/GetAllMarket',
                request_serializer=market__pb2.Empty.SerializeToString,
                response_deserializer=market__pb2.MarketList.FromString,
                _registered_method=True)
        self.CreateMarket = channel.unary_unary(
                '/MarketService/CreateMarket',
                request_serializer=market__pb2.Market.SerializeToString,
                response_deserializer=market__pb2.Market.FromString,
                _registered_method=True)
        self.GetMarket = channel.unary_unary(
                '/MarketService/GetMarket',
                request_serializer=market__pb2.MarketId.SerializeToString,
                response_deserializer=market__pb2.Market.FromString,
                _registered_method=True)
        self.UpdateMarket = channel.unary_unary(
                '/MarketService/UpdateMarket',
                request_serializer=market__pb2.Market.SerializeToString,
                response_deserializer=market__pb2.Market.FromString,
                _registered_method=True)
        self.DeleteMarket = channel.unary_unary(
                '/MarketService/DeleteMarket',
                request_serializer=market__pb2.MarketId.SerializeToString,
                response_deserializer=market__pb2.Empty.FromString,
                _registered_method=True)


class MarketServiceServicer(object):
    """Service definition
    """

    def GetAllMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMarket,
                    request_deserializer=market__pb2.Empty.FromString,
                    response_serializer=market__pb2.MarketList.SerializeToString,
            ),
            'CreateMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMarket,
                    request_deserializer=market__pb2.Market.FromString,
                    response_serializer=market__pb2.Market.SerializeToString,
            ),
            'GetMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarket,
                    request_deserializer=market__pb2.MarketId.FromString,
                    response_serializer=market__pb2.Market.SerializeToString,
            ),
            'UpdateMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMarket,
                    request_deserializer=market__pb2.Market.FromString,
                    response_serializer=market__pb2.Market.SerializeToString,
            ),
            'DeleteMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMarket,
                    request_deserializer=market__pb2.MarketId.FromString,
                    response_serializer=market__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MarketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketService(object):
    """Service definition
    """

    @staticmethod
    def GetAllMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/GetAllMarket',
            market__pb2.Empty.SerializeToString,
            market__pb2.MarketList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/CreateMarket',
            market__pb2.Market.SerializeToString,
            market__pb2.Market.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/GetMarket',
            market__pb2.MarketId.SerializeToString,
            market__pb2.Market.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/UpdateMarket',
            market__pb2.Market.SerializeToString,
            market__pb2.Market.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/DeleteMarket',
            market__pb2.MarketId.SerializeToString,
            market__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
